# Homebrew formula for cmux (macOS).
#
# PORT STATUS: authored on Linux, NOT yet validated with `brew install`. The
# url/sha256 are placeholders; a real release fills them from a tagged tarball.
# The original macOS-era repo shipped a `homebrew-cmux/` tap (see CHANGELOG.md)
# — mine that git history for a battle-tested formula before finalizing.
# See specs/cmux-macos-extensibility.html Phase 5.
#
# This builds from source against Homebrew GTK4. An alternative distribution is
# a Cask wrapping the notarized .dmg from build-dmg.sh; pick one before v1.
class Cmux < Formula
  desc "GPU-accelerated terminal multiplexer for AI coding agents"
  homepage "https://github.com/manaflow-ai/cmux"
  url "https://github.com/manaflow-ai/cmux/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license "MIT"
  head "https://github.com/manaflow-ai/cmux.git", branch: "main"

  depends_on "pkg-config" => :build
  depends_on "rust" => :build
  depends_on "zig" => :build
  depends_on "gtk4"
  depends_on "oniguruma"

  def install
    # Build the vendored ghostty static lib, then the Rust workspace.
    system "./scripts/setup-macos.sh"
    system "cargo", "build", "--release", "--locked"
    bin.install "target/release/cmux-app"
    bin.install "target/release/cmux"

    # Shell completions generated by the cmux-generate helper (mirrors the
    # Linux packaging), if present.
    generate_completions_from_executable(bin/"cmux", "completions") if (bin/"cmux").exist?
  end

  test do
    # The CLI reports its version without needing a running cmux-app.
    assert_match "cmux", shell_output("#{bin}/cmux --help")
  end
end
